services:
    train-api:
        build:
            context: .
            dockerfile: Dockerfile
            target: runtime
            args:
                - APP_NAME=${APP_NAME}
                - APP_VERSION=${APP_VERSION}
                - NODE_ENV=${NODE_ENV}
        image: ${APP_NAME}:${APP_VERSION}
        environment:
            - MONGO_URI=${MONGO_URI}
            - NODE_ENV=${NODE_ENV}
        ports:
            - 3000:3000

    train-test:
        build:
            context: .
            dockerfile: Dockerfile
            target: test
        environment:
            - MONGO_URI=mongodb://root:example@mongodb-test:27017/
            - NODE_ENV=test
            - SECRET_CODE=test-secret-key
        ports:
            - 3000:3000
        depends_on:
            - mongodb-test


    mongodb-test:
        image: mongodb/mongodb-atlas-local:7.0.7
        ports:
            - "27017:27017"
        environment:
            - MONGODB_INITDB_DATABASE=train_test
            - MONGODB_INITDB_ROOT_USERNAME=root
            - MONGODB_INITDB_ROOT_PASSWORD=example
        volumes:
            - mongodb_test_data:/data/db

volumes:
    mongodb_test_data
